// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCareSystemAtHome.Data.Models;

[Table("blogs")]
public partial class Blog
{
    [Key]
    [Column("blog_id")]
    public long BlogId { get; set; }

    [Column("title")]
    [StringLength(255)]
    public string Title { get; set; }

    [Column("user_id")]
    public long UserId { get; set; }

    [Column("content")]
    [StringLength(255)]
    [Unicode(false)]
    public string Content { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Blogs")]
    public virtual User User { get; set; }
}