// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCareSystemAtHome.Data.Models;

[Table("koi_fish")]
public partial class KoiFish
{
    [Key]
    [Column("fish_id")]
    public long FishId { get; set; }

    [Column("fish_name")]
    [StringLength(255)]
    public string FishName { get; set; }

    [Column("user_id")]
    public long UserId { get; set; }

    [Column("pond_id")]
    public long? PondId { get; set; }

    [Column("image_url")]
    [StringLength(255)]
    public string ImageUrl { get; set; }

    [Column("body_shape")]
    [StringLength(255)]
    public string BodyShape { get; set; }

    [Column("age")]
    public long? Age { get; set; }

    [Column("size", TypeName = "decimal(10, 2)")]
    public decimal? Size { get; set; }

    [Column("weight", TypeName = "decimal(10, 2)")]
    public decimal? Weight { get; set; }

    [Column("gender")]
    [StringLength(255)]
    public string Gender { get; set; }

    [Column("breed")]
    [StringLength(255)]
    public string Breed { get; set; }

    [Column("origin")]
    [StringLength(255)]
    public string Origin { get; set; }

    [Column("price", TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [InverseProperty("Fish")]
    public virtual ICollection<KoiGrowthLog> KoiGrowthLogs { get; set; } = new List<KoiGrowthLog>();

    [ForeignKey("PondId")]
    [InverseProperty("KoiFishes")]
    public virtual Pond Pond { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("KoiFishes")]
    public virtual User User { get; set; }
}