// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCareSystemAtHome.Data.Models;

[Table("koi_growth_logs")]
public partial class KoiGrowthLog
{
    [Key]
    [Column("log_id")]
    public long LogId { get; set; }

    [Column("fish_id")]
    public long? FishId { get; set; }

    [Column("growth_date")]
    public long? GrowthDate { get; set; }

    [Column("size", TypeName = "decimal(10, 2)")]
    public decimal? Size { get; set; }

    [Column("weight", TypeName = "decimal(10, 2)")]
    public decimal? Weight { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [Column("food_recomment", TypeName = "decimal(8, 2)")]
    public decimal FoodRecomment { get; set; }

    [ForeignKey("FishId")]
    [InverseProperty("KoiGrowthLogs")]
    public virtual KoiFish Fish { get; set; }
}