// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCareSystemAtHome.Data.Models;

[Table("ponds")]
public partial class Pond
{
    [Key]
    [Column("pond_id")]
    public long PondId { get; set; }

    [Column("pond_name")]
    [StringLength(255)]
    public string PondName { get; set; }

    [Column("image_url")]
    [StringLength(255)]
    public string ImageUrl { get; set; }

    [Column("size", TypeName = "decimal(10, 2)")]
    public decimal? Size { get; set; }

    [Column("depth", TypeName = "decimal(10, 2)")]
    public decimal? Depth { get; set; }

    [Column("volume", TypeName = "decimal(10, 2)")]
    public decimal? Volume { get; set; }

    [Column("drain_count")]
    public long? DrainCount { get; set; }

    [Column("pump_capacity", TypeName = "decimal(10, 2)")]
    public decimal? PumpCapacity { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [Column("user_id")]
    public long UserId { get; set; }

    [Column("skimmer_count")]
    public long SkimmerCount { get; set; }

    [InverseProperty("Pond")]
    public virtual ICollection<KoiFish> KoiFishes { get; set; } = new List<KoiFish>();

    [ForeignKey("UserId")]
    [InverseProperty("Ponds")]
    public virtual User User { get; set; }

    [InverseProperty("Pond")]
    public virtual ICollection<WaterParameter> WaterParameters { get; set; } = new List<WaterParameter>();
}