// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiCareSystemAtHome.Data.Models;

[Table("water_parameters")]
public partial class WaterParameter
{
    [Key]
    [Column("parameter_id")]
    public long ParameterId { get; set; }

    [Column("pond_id")]
    public long? PondId { get; set; }

    [Column("measurement_date")]
    public long? MeasurementDate { get; set; }

    [Column("temperature", TypeName = "decimal(10, 2)")]
    public decimal? Temperature { get; set; }

    [Column("salinity", TypeName = "decimal(10, 2)")]
    public decimal? Salinity { get; set; }

    [Column("ph", TypeName = "decimal(10, 2)")]
    public decimal? Ph { get; set; }

    [Column("o2", TypeName = "decimal(10, 2)")]
    public decimal? O2 { get; set; }

    [Column("no2", TypeName = "decimal(10, 2)")]
    public decimal? No2 { get; set; }

    [Column("no3", TypeName = "decimal(10, 2)")]
    public decimal? No3 { get; set; }

    [Column("po4", TypeName = "decimal(10, 2)")]
    public decimal? Po4 { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("PondId")]
    [InverseProperty("WaterParameters")]
    public virtual Pond Pond { get; set; }
}